import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import {ThemeProvider} from '@/theme/theme-provider'
import React from 'react'
import './globals.css'

const fontSans = Inter({subsets: ['latin']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning>
      <head>
        <title>Portfolio</title>
      </head>
      <body
        className={fontSans.className}
        suppressHydrationWarning>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange>
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
