import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import {ThemeProvider} from '@/theme/theme-provider'
import React from 'react'
import './globals.css'
import {cn} from '@/lib/utils'
import {Toaster} from '@/components/ui/sonner'
import Footer from '@/features/footer'

const fontSans = Inter({subsets: ['latin']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className="scroll-smooth">
      <head>
        <title>Portfolio</title>
        <meta charSet={'utf-8'} />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
      </head>
      <body
        className={cn(fontSans.className, 'w-full')}
        suppressHydrationWarning>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange>
          {children}
        </ThemeProvider>
        <Toaster />

        <Footer />
      </body>
    </html>
  )
}
